### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by IceKhan13** [IceKhan13/medical_database#2]
Create layout for system using bootstrap 3.
Pages wanted:
- login
- main
- doctor view
- patient view
- lab guy view
- warehouse view,

other pages coming soon...

**Comment by IceKhan13** [comment]
there are some layout in /static/layout folder

**Comment by addi1993** [comment]
Somebody stop Iskandar, he is gonna make the project by his own:)

**Comment by IceKhan13** [comment]
TODO: make a list of all available view and implement them in HTML using /static/layout/main.html as a base

**Comment by IceKhan13** [comment]
[DMD - pages.pdf](https://github.com/IceKhan13/medical_database/files/589968/DMD.-.pages.pdf)

**Comment by IceKhan13** [comment]
TODO: fix table lab_exam

**Comment by IceKhan13** [comment]
close for now
